version: '3'

services:
  nest-js:
    build:
      context: . 
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3307
      MYSQL_USER: root
      MYSQL_PASSWORD: Arwa0000
      MYSQL_DATABASE: hcareDB
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports: 
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: Arwa0000
      MYSQL_DATABASE: hcareDB

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Arwa0000
